// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package GamePlayerTest;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GamePlayerTest.TestMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *浮点数
     *=1代表唯一编号
     * </pre>
     *
     * <code>float testF = 1;</code>
     * @return The testF.
     */
    float getTestF();

    /**
     * <code>double testD = 2;</code>
     * @return The testD.
     */
    double getTestD();

    /**
     * <pre>
     *变长编码
     * </pre>
     *
     * <code>int32 testInt32 = 3;</code>
     * @return The testInt32.
     */
    int getTestInt32();

    /**
     * <pre>
     *用于表示负数的整数
     * </pre>
     *
     * <code>int64 testInt64 = 4;</code>
     * @return The testInt64.
     */
    long getTestInt64();

    /**
     * <pre>
     *用于表示负数的整数
     * </pre>
     *
     * <code>sint32 testSInt32 = 5;</code>
     * @return The testSInt32.
     */
    int getTestSInt32();

    /**
     * <code>sint64 testSInt64 = 6;</code>
     * @return The testSInt64.
     */
    long getTestSInt64();

    /**
     * <pre>
     *无符号变长编码
     * </pre>
     *
     * <code>uint32 testUInt32 = 7;</code>
     * @return The testUInt32.
     */
    int getTestUInt32();

    /**
     * <code>uint64 testULong = 8;</code>
     * @return The testULong.
     */
    long getTestULong();

    /**
     * <pre>
     *固定字节数的类型
     * </pre>
     *
     * <code>fixed32 testFixed32 = 9;</code>
     * @return The testFixed32.
     */
    int getTestFixed32();

    /**
     * <code>fixed64 testFixed64 = 10;</code>
     * @return The testFixed64.
     */
    long getTestFixed64();

    /**
     * <code>sfixed32 testSFixed32 = 11;</code>
     * @return The testSFixed32.
     */
    int getTestSFixed32();

    /**
     * <code>sfixed64 testSFixed64 = 12;</code>
     * @return The testSFixed64.
     */
    long getTestSFixed64();

    /**
     * <pre>
     *其他类型
     * </pre>
     *
     * <code>bool testBool = 13;</code>
     * @return The testBool.
     */
    boolean getTestBool();

    /**
     * <code>string testStr = 14;</code>
     * @return The testStr.
     */
    java.lang.String getTestStr();
    /**
     * <code>string testStr = 14;</code>
     * @return The bytes for testStr.
     */
    com.google.protobuf.ByteString
        getTestStrBytes();

    /**
     * <code>bytes testBytes = 15;</code>
     * @return The testBytes.
     */
    com.google.protobuf.ByteString getTestBytes();

    /**
     * <code>repeated int32 listInt = 16;</code>
     * @return A list containing the listInt.
     */
    java.util.List<java.lang.Integer> getListIntList();
    /**
     * <code>repeated int32 listInt = 16;</code>
     * @return The count of listInt.
     */
    int getListIntCount();
    /**
     * <code>repeated int32 listInt = 16;</code>
     * @param index The index of the element to return.
     * @return The listInt at the given index.
     */
    int getListInt(int index);

    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */
    int getTestMapCount();
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */
    boolean containsTestMap(
        int key);
    /**
     * Use {@link #getTestMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getTestMap();
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getTestMapMap();
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */

    /* nullable */
java.lang.String getTestMapOrDefault(
        int key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */

    java.lang.String getTestMapOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code GamePlayerTest.TestMsg}
   */
  public static final class TestMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GamePlayerTest.TestMsg)
      TestMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestMsg.newBuilder() to construct.
    private TestMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestMsg() {
      testStr_ = "";
      testBytes_ = com.google.protobuf.ByteString.EMPTY;
      listInt_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              testF_ = input.readFloat();
              break;
            }
            case 17: {

              testD_ = input.readDouble();
              break;
            }
            case 24: {

              testInt32_ = input.readInt32();
              break;
            }
            case 32: {

              testInt64_ = input.readInt64();
              break;
            }
            case 40: {

              testSInt32_ = input.readSInt32();
              break;
            }
            case 48: {

              testSInt64_ = input.readSInt64();
              break;
            }
            case 56: {

              testUInt32_ = input.readUInt32();
              break;
            }
            case 64: {

              testULong_ = input.readUInt64();
              break;
            }
            case 77: {

              testFixed32_ = input.readFixed32();
              break;
            }
            case 81: {

              testFixed64_ = input.readFixed64();
              break;
            }
            case 93: {

              testSFixed32_ = input.readSFixed32();
              break;
            }
            case 97: {

              testSFixed64_ = input.readSFixed64();
              break;
            }
            case 104: {

              testBool_ = input.readBool();
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              testStr_ = s;
              break;
            }
            case 122: {

              testBytes_ = input.readBytes();
              break;
            }
            case 128: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                listInt_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              listInt_.addInt(input.readInt32());
              break;
            }
            case 130: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                listInt_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                listInt_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 138: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                testMap_ = com.google.protobuf.MapField.newMapField(
                    TestMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              testMap__ = input.readMessage(
                  TestMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              testMap_.getMutableMap().put(
                  testMap__.getKey(), testMap__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          listInt_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GamePlayerTest.Test.internal_static_GamePlayerTest_TestMsg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 17:
          return internalGetTestMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GamePlayerTest.Test.internal_static_GamePlayerTest_TestMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GamePlayerTest.Test.TestMsg.class, GamePlayerTest.Test.TestMsg.Builder.class);
    }

    public static final int TESTF_FIELD_NUMBER = 1;
    private float testF_;
    /**
     * <pre>
     *浮点数
     *=1代表唯一编号
     * </pre>
     *
     * <code>float testF = 1;</code>
     * @return The testF.
     */
    @java.lang.Override
    public float getTestF() {
      return testF_;
    }

    public static final int TESTD_FIELD_NUMBER = 2;
    private double testD_;
    /**
     * <code>double testD = 2;</code>
     * @return The testD.
     */
    @java.lang.Override
    public double getTestD() {
      return testD_;
    }

    public static final int TESTINT32_FIELD_NUMBER = 3;
    private int testInt32_;
    /**
     * <pre>
     *变长编码
     * </pre>
     *
     * <code>int32 testInt32 = 3;</code>
     * @return The testInt32.
     */
    @java.lang.Override
    public int getTestInt32() {
      return testInt32_;
    }

    public static final int TESTINT64_FIELD_NUMBER = 4;
    private long testInt64_;
    /**
     * <pre>
     *用于表示负数的整数
     * </pre>
     *
     * <code>int64 testInt64 = 4;</code>
     * @return The testInt64.
     */
    @java.lang.Override
    public long getTestInt64() {
      return testInt64_;
    }

    public static final int TESTSINT32_FIELD_NUMBER = 5;
    private int testSInt32_;
    /**
     * <pre>
     *用于表示负数的整数
     * </pre>
     *
     * <code>sint32 testSInt32 = 5;</code>
     * @return The testSInt32.
     */
    @java.lang.Override
    public int getTestSInt32() {
      return testSInt32_;
    }

    public static final int TESTSINT64_FIELD_NUMBER = 6;
    private long testSInt64_;
    /**
     * <code>sint64 testSInt64 = 6;</code>
     * @return The testSInt64.
     */
    @java.lang.Override
    public long getTestSInt64() {
      return testSInt64_;
    }

    public static final int TESTUINT32_FIELD_NUMBER = 7;
    private int testUInt32_;
    /**
     * <pre>
     *无符号变长编码
     * </pre>
     *
     * <code>uint32 testUInt32 = 7;</code>
     * @return The testUInt32.
     */
    @java.lang.Override
    public int getTestUInt32() {
      return testUInt32_;
    }

    public static final int TESTULONG_FIELD_NUMBER = 8;
    private long testULong_;
    /**
     * <code>uint64 testULong = 8;</code>
     * @return The testULong.
     */
    @java.lang.Override
    public long getTestULong() {
      return testULong_;
    }

    public static final int TESTFIXED32_FIELD_NUMBER = 9;
    private int testFixed32_;
    /**
     * <pre>
     *固定字节数的类型
     * </pre>
     *
     * <code>fixed32 testFixed32 = 9;</code>
     * @return The testFixed32.
     */
    @java.lang.Override
    public int getTestFixed32() {
      return testFixed32_;
    }

    public static final int TESTFIXED64_FIELD_NUMBER = 10;
    private long testFixed64_;
    /**
     * <code>fixed64 testFixed64 = 10;</code>
     * @return The testFixed64.
     */
    @java.lang.Override
    public long getTestFixed64() {
      return testFixed64_;
    }

    public static final int TESTSFIXED32_FIELD_NUMBER = 11;
    private int testSFixed32_;
    /**
     * <code>sfixed32 testSFixed32 = 11;</code>
     * @return The testSFixed32.
     */
    @java.lang.Override
    public int getTestSFixed32() {
      return testSFixed32_;
    }

    public static final int TESTSFIXED64_FIELD_NUMBER = 12;
    private long testSFixed64_;
    /**
     * <code>sfixed64 testSFixed64 = 12;</code>
     * @return The testSFixed64.
     */
    @java.lang.Override
    public long getTestSFixed64() {
      return testSFixed64_;
    }

    public static final int TESTBOOL_FIELD_NUMBER = 13;
    private boolean testBool_;
    /**
     * <pre>
     *其他类型
     * </pre>
     *
     * <code>bool testBool = 13;</code>
     * @return The testBool.
     */
    @java.lang.Override
    public boolean getTestBool() {
      return testBool_;
    }

    public static final int TESTSTR_FIELD_NUMBER = 14;
    private volatile java.lang.Object testStr_;
    /**
     * <code>string testStr = 14;</code>
     * @return The testStr.
     */
    @java.lang.Override
    public java.lang.String getTestStr() {
      java.lang.Object ref = testStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testStr_ = s;
        return s;
      }
    }
    /**
     * <code>string testStr = 14;</code>
     * @return The bytes for testStr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTestStrBytes() {
      java.lang.Object ref = testStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TESTBYTES_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString testBytes_;
    /**
     * <code>bytes testBytes = 15;</code>
     * @return The testBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTestBytes() {
      return testBytes_;
    }

    public static final int LISTINT_FIELD_NUMBER = 16;
    private com.google.protobuf.Internal.IntList listInt_;
    /**
     * <code>repeated int32 listInt = 16;</code>
     * @return A list containing the listInt.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getListIntList() {
      return listInt_;
    }
    /**
     * <code>repeated int32 listInt = 16;</code>
     * @return The count of listInt.
     */
    public int getListIntCount() {
      return listInt_.size();
    }
    /**
     * <code>repeated int32 listInt = 16;</code>
     * @param index The index of the element to return.
     * @return The listInt at the given index.
     */
    public int getListInt(int index) {
      return listInt_.getInt(index);
    }
    private int listIntMemoizedSerializedSize = -1;

    public static final int TESTMAP_FIELD_NUMBER = 17;
    private static final class TestMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  GamePlayerTest.Test.internal_static_GamePlayerTest_TestMsg_TestMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> testMap_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetTestMap() {
      if (testMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TestMapDefaultEntryHolder.defaultEntry);
      }
      return testMap_;
    }

    public int getTestMapCount() {
      return internalGetTestMap().getMap().size();
    }
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */

    @java.lang.Override
    public boolean containsTestMap(
        int key) {
      
      return internalGetTestMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTestMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getTestMap() {
      return getTestMapMap();
    }
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.String> getTestMapMap() {
      return internalGetTestMap().getMap();
    }
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */
    @java.lang.Override

    public java.lang.String getTestMapOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetTestMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *字典Dictionary
     * </pre>
     *
     * <code>map&lt;int32, string&gt; testMap = 17;</code>
     */
    @java.lang.Override

    public java.lang.String getTestMapOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetTestMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (java.lang.Float.floatToRawIntBits(testF_) != 0) {
        output.writeFloat(1, testF_);
      }
      if (java.lang.Double.doubleToRawLongBits(testD_) != 0) {
        output.writeDouble(2, testD_);
      }
      if (testInt32_ != 0) {
        output.writeInt32(3, testInt32_);
      }
      if (testInt64_ != 0L) {
        output.writeInt64(4, testInt64_);
      }
      if (testSInt32_ != 0) {
        output.writeSInt32(5, testSInt32_);
      }
      if (testSInt64_ != 0L) {
        output.writeSInt64(6, testSInt64_);
      }
      if (testUInt32_ != 0) {
        output.writeUInt32(7, testUInt32_);
      }
      if (testULong_ != 0L) {
        output.writeUInt64(8, testULong_);
      }
      if (testFixed32_ != 0) {
        output.writeFixed32(9, testFixed32_);
      }
      if (testFixed64_ != 0L) {
        output.writeFixed64(10, testFixed64_);
      }
      if (testSFixed32_ != 0) {
        output.writeSFixed32(11, testSFixed32_);
      }
      if (testSFixed64_ != 0L) {
        output.writeSFixed64(12, testSFixed64_);
      }
      if (testBool_ != false) {
        output.writeBool(13, testBool_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testStr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, testStr_);
      }
      if (!testBytes_.isEmpty()) {
        output.writeBytes(15, testBytes_);
      }
      if (getListIntList().size() > 0) {
        output.writeUInt32NoTag(130);
        output.writeUInt32NoTag(listIntMemoizedSerializedSize);
      }
      for (int i = 0; i < listInt_.size(); i++) {
        output.writeInt32NoTag(listInt_.getInt(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetTestMap(),
          TestMapDefaultEntryHolder.defaultEntry,
          17);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(testF_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, testF_);
      }
      if (java.lang.Double.doubleToRawLongBits(testD_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, testD_);
      }
      if (testInt32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, testInt32_);
      }
      if (testInt64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, testInt64_);
      }
      if (testSInt32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, testSInt32_);
      }
      if (testSInt64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(6, testSInt64_);
      }
      if (testUInt32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, testUInt32_);
      }
      if (testULong_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, testULong_);
      }
      if (testFixed32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(9, testFixed32_);
      }
      if (testFixed64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(10, testFixed64_);
      }
      if (testSFixed32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(11, testSFixed32_);
      }
      if (testSFixed64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(12, testSFixed64_);
      }
      if (testBool_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, testBool_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testStr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, testStr_);
      }
      if (!testBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, testBytes_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < listInt_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(listInt_.getInt(i));
        }
        size += dataSize;
        if (!getListIntList().isEmpty()) {
          size += 2;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        listIntMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetTestMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        testMap__ = TestMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(17, testMap__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GamePlayerTest.Test.TestMsg)) {
        return super.equals(obj);
      }
      GamePlayerTest.Test.TestMsg other = (GamePlayerTest.Test.TestMsg) obj;

      if (java.lang.Float.floatToIntBits(getTestF())
          != java.lang.Float.floatToIntBits(
              other.getTestF())) return false;
      if (java.lang.Double.doubleToLongBits(getTestD())
          != java.lang.Double.doubleToLongBits(
              other.getTestD())) return false;
      if (getTestInt32()
          != other.getTestInt32()) return false;
      if (getTestInt64()
          != other.getTestInt64()) return false;
      if (getTestSInt32()
          != other.getTestSInt32()) return false;
      if (getTestSInt64()
          != other.getTestSInt64()) return false;
      if (getTestUInt32()
          != other.getTestUInt32()) return false;
      if (getTestULong()
          != other.getTestULong()) return false;
      if (getTestFixed32()
          != other.getTestFixed32()) return false;
      if (getTestFixed64()
          != other.getTestFixed64()) return false;
      if (getTestSFixed32()
          != other.getTestSFixed32()) return false;
      if (getTestSFixed64()
          != other.getTestSFixed64()) return false;
      if (getTestBool()
          != other.getTestBool()) return false;
      if (!getTestStr()
          .equals(other.getTestStr())) return false;
      if (!getTestBytes()
          .equals(other.getTestBytes())) return false;
      if (!getListIntList()
          .equals(other.getListIntList())) return false;
      if (!internalGetTestMap().equals(
          other.internalGetTestMap())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TESTF_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTestF());
      hash = (37 * hash) + TESTD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTestD()));
      hash = (37 * hash) + TESTINT32_FIELD_NUMBER;
      hash = (53 * hash) + getTestInt32();
      hash = (37 * hash) + TESTINT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTestInt64());
      hash = (37 * hash) + TESTSINT32_FIELD_NUMBER;
      hash = (53 * hash) + getTestSInt32();
      hash = (37 * hash) + TESTSINT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTestSInt64());
      hash = (37 * hash) + TESTUINT32_FIELD_NUMBER;
      hash = (53 * hash) + getTestUInt32();
      hash = (37 * hash) + TESTULONG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTestULong());
      hash = (37 * hash) + TESTFIXED32_FIELD_NUMBER;
      hash = (53 * hash) + getTestFixed32();
      hash = (37 * hash) + TESTFIXED64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTestFixed64());
      hash = (37 * hash) + TESTSFIXED32_FIELD_NUMBER;
      hash = (53 * hash) + getTestSFixed32();
      hash = (37 * hash) + TESTSFIXED64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTestSFixed64());
      hash = (37 * hash) + TESTBOOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTestBool());
      hash = (37 * hash) + TESTSTR_FIELD_NUMBER;
      hash = (53 * hash) + getTestStr().hashCode();
      hash = (37 * hash) + TESTBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getTestBytes().hashCode();
      if (getListIntCount() > 0) {
        hash = (37 * hash) + LISTINT_FIELD_NUMBER;
        hash = (53 * hash) + getListIntList().hashCode();
      }
      if (!internalGetTestMap().getMap().isEmpty()) {
        hash = (37 * hash) + TESTMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTestMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GamePlayerTest.Test.TestMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GamePlayerTest.Test.TestMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GamePlayerTest.Test.TestMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GamePlayerTest.Test.TestMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GamePlayerTest.Test.TestMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GamePlayerTest.TestMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GamePlayerTest.TestMsg)
        GamePlayerTest.Test.TestMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GamePlayerTest.Test.internal_static_GamePlayerTest_TestMsg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 17:
            return internalGetTestMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 17:
            return internalGetMutableTestMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GamePlayerTest.Test.internal_static_GamePlayerTest_TestMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GamePlayerTest.Test.TestMsg.class, GamePlayerTest.Test.TestMsg.Builder.class);
      }

      // Construct using GamePlayerTest.Test.TestMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        testF_ = 0F;

        testD_ = 0D;

        testInt32_ = 0;

        testInt64_ = 0L;

        testSInt32_ = 0;

        testSInt64_ = 0L;

        testUInt32_ = 0;

        testULong_ = 0L;

        testFixed32_ = 0;

        testFixed64_ = 0L;

        testSFixed32_ = 0;

        testSFixed64_ = 0L;

        testBool_ = false;

        testStr_ = "";

        testBytes_ = com.google.protobuf.ByteString.EMPTY;

        listInt_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableTestMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GamePlayerTest.Test.internal_static_GamePlayerTest_TestMsg_descriptor;
      }

      @java.lang.Override
      public GamePlayerTest.Test.TestMsg getDefaultInstanceForType() {
        return GamePlayerTest.Test.TestMsg.getDefaultInstance();
      }

      @java.lang.Override
      public GamePlayerTest.Test.TestMsg build() {
        GamePlayerTest.Test.TestMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GamePlayerTest.Test.TestMsg buildPartial() {
        GamePlayerTest.Test.TestMsg result = new GamePlayerTest.Test.TestMsg(this);
        int from_bitField0_ = bitField0_;
        result.testF_ = testF_;
        result.testD_ = testD_;
        result.testInt32_ = testInt32_;
        result.testInt64_ = testInt64_;
        result.testSInt32_ = testSInt32_;
        result.testSInt64_ = testSInt64_;
        result.testUInt32_ = testUInt32_;
        result.testULong_ = testULong_;
        result.testFixed32_ = testFixed32_;
        result.testFixed64_ = testFixed64_;
        result.testSFixed32_ = testSFixed32_;
        result.testSFixed64_ = testSFixed64_;
        result.testBool_ = testBool_;
        result.testStr_ = testStr_;
        result.testBytes_ = testBytes_;
        if (((bitField0_ & 0x00000001) != 0)) {
          listInt_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.listInt_ = listInt_;
        result.testMap_ = internalGetTestMap();
        result.testMap_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GamePlayerTest.Test.TestMsg) {
          return mergeFrom((GamePlayerTest.Test.TestMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GamePlayerTest.Test.TestMsg other) {
        if (other == GamePlayerTest.Test.TestMsg.getDefaultInstance()) return this;
        if (other.getTestF() != 0F) {
          setTestF(other.getTestF());
        }
        if (other.getTestD() != 0D) {
          setTestD(other.getTestD());
        }
        if (other.getTestInt32() != 0) {
          setTestInt32(other.getTestInt32());
        }
        if (other.getTestInt64() != 0L) {
          setTestInt64(other.getTestInt64());
        }
        if (other.getTestSInt32() != 0) {
          setTestSInt32(other.getTestSInt32());
        }
        if (other.getTestSInt64() != 0L) {
          setTestSInt64(other.getTestSInt64());
        }
        if (other.getTestUInt32() != 0) {
          setTestUInt32(other.getTestUInt32());
        }
        if (other.getTestULong() != 0L) {
          setTestULong(other.getTestULong());
        }
        if (other.getTestFixed32() != 0) {
          setTestFixed32(other.getTestFixed32());
        }
        if (other.getTestFixed64() != 0L) {
          setTestFixed64(other.getTestFixed64());
        }
        if (other.getTestSFixed32() != 0) {
          setTestSFixed32(other.getTestSFixed32());
        }
        if (other.getTestSFixed64() != 0L) {
          setTestSFixed64(other.getTestSFixed64());
        }
        if (other.getTestBool() != false) {
          setTestBool(other.getTestBool());
        }
        if (!other.getTestStr().isEmpty()) {
          testStr_ = other.testStr_;
          onChanged();
        }
        if (other.getTestBytes() != com.google.protobuf.ByteString.EMPTY) {
          setTestBytes(other.getTestBytes());
        }
        if (!other.listInt_.isEmpty()) {
          if (listInt_.isEmpty()) {
            listInt_ = other.listInt_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListIntIsMutable();
            listInt_.addAll(other.listInt_);
          }
          onChanged();
        }
        internalGetMutableTestMap().mergeFrom(
            other.internalGetTestMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GamePlayerTest.Test.TestMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GamePlayerTest.Test.TestMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float testF_ ;
      /**
       * <pre>
       *浮点数
       *=1代表唯一编号
       * </pre>
       *
       * <code>float testF = 1;</code>
       * @return The testF.
       */
      @java.lang.Override
      public float getTestF() {
        return testF_;
      }
      /**
       * <pre>
       *浮点数
       *=1代表唯一编号
       * </pre>
       *
       * <code>float testF = 1;</code>
       * @param value The testF to set.
       * @return This builder for chaining.
       */
      public Builder setTestF(float value) {
        
        testF_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *浮点数
       *=1代表唯一编号
       * </pre>
       *
       * <code>float testF = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestF() {
        
        testF_ = 0F;
        onChanged();
        return this;
      }

      private double testD_ ;
      /**
       * <code>double testD = 2;</code>
       * @return The testD.
       */
      @java.lang.Override
      public double getTestD() {
        return testD_;
      }
      /**
       * <code>double testD = 2;</code>
       * @param value The testD to set.
       * @return This builder for chaining.
       */
      public Builder setTestD(double value) {
        
        testD_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double testD = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestD() {
        
        testD_ = 0D;
        onChanged();
        return this;
      }

      private int testInt32_ ;
      /**
       * <pre>
       *变长编码
       * </pre>
       *
       * <code>int32 testInt32 = 3;</code>
       * @return The testInt32.
       */
      @java.lang.Override
      public int getTestInt32() {
        return testInt32_;
      }
      /**
       * <pre>
       *变长编码
       * </pre>
       *
       * <code>int32 testInt32 = 3;</code>
       * @param value The testInt32 to set.
       * @return This builder for chaining.
       */
      public Builder setTestInt32(int value) {
        
        testInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *变长编码
       * </pre>
       *
       * <code>int32 testInt32 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestInt32() {
        
        testInt32_ = 0;
        onChanged();
        return this;
      }

      private long testInt64_ ;
      /**
       * <pre>
       *用于表示负数的整数
       * </pre>
       *
       * <code>int64 testInt64 = 4;</code>
       * @return The testInt64.
       */
      @java.lang.Override
      public long getTestInt64() {
        return testInt64_;
      }
      /**
       * <pre>
       *用于表示负数的整数
       * </pre>
       *
       * <code>int64 testInt64 = 4;</code>
       * @param value The testInt64 to set.
       * @return This builder for chaining.
       */
      public Builder setTestInt64(long value) {
        
        testInt64_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于表示负数的整数
       * </pre>
       *
       * <code>int64 testInt64 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestInt64() {
        
        testInt64_ = 0L;
        onChanged();
        return this;
      }

      private int testSInt32_ ;
      /**
       * <pre>
       *用于表示负数的整数
       * </pre>
       *
       * <code>sint32 testSInt32 = 5;</code>
       * @return The testSInt32.
       */
      @java.lang.Override
      public int getTestSInt32() {
        return testSInt32_;
      }
      /**
       * <pre>
       *用于表示负数的整数
       * </pre>
       *
       * <code>sint32 testSInt32 = 5;</code>
       * @param value The testSInt32 to set.
       * @return This builder for chaining.
       */
      public Builder setTestSInt32(int value) {
        
        testSInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用于表示负数的整数
       * </pre>
       *
       * <code>sint32 testSInt32 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestSInt32() {
        
        testSInt32_ = 0;
        onChanged();
        return this;
      }

      private long testSInt64_ ;
      /**
       * <code>sint64 testSInt64 = 6;</code>
       * @return The testSInt64.
       */
      @java.lang.Override
      public long getTestSInt64() {
        return testSInt64_;
      }
      /**
       * <code>sint64 testSInt64 = 6;</code>
       * @param value The testSInt64 to set.
       * @return This builder for chaining.
       */
      public Builder setTestSInt64(long value) {
        
        testSInt64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 testSInt64 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestSInt64() {
        
        testSInt64_ = 0L;
        onChanged();
        return this;
      }

      private int testUInt32_ ;
      /**
       * <pre>
       *无符号变长编码
       * </pre>
       *
       * <code>uint32 testUInt32 = 7;</code>
       * @return The testUInt32.
       */
      @java.lang.Override
      public int getTestUInt32() {
        return testUInt32_;
      }
      /**
       * <pre>
       *无符号变长编码
       * </pre>
       *
       * <code>uint32 testUInt32 = 7;</code>
       * @param value The testUInt32 to set.
       * @return This builder for chaining.
       */
      public Builder setTestUInt32(int value) {
        
        testUInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *无符号变长编码
       * </pre>
       *
       * <code>uint32 testUInt32 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestUInt32() {
        
        testUInt32_ = 0;
        onChanged();
        return this;
      }

      private long testULong_ ;
      /**
       * <code>uint64 testULong = 8;</code>
       * @return The testULong.
       */
      @java.lang.Override
      public long getTestULong() {
        return testULong_;
      }
      /**
       * <code>uint64 testULong = 8;</code>
       * @param value The testULong to set.
       * @return This builder for chaining.
       */
      public Builder setTestULong(long value) {
        
        testULong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 testULong = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestULong() {
        
        testULong_ = 0L;
        onChanged();
        return this;
      }

      private int testFixed32_ ;
      /**
       * <pre>
       *固定字节数的类型
       * </pre>
       *
       * <code>fixed32 testFixed32 = 9;</code>
       * @return The testFixed32.
       */
      @java.lang.Override
      public int getTestFixed32() {
        return testFixed32_;
      }
      /**
       * <pre>
       *固定字节数的类型
       * </pre>
       *
       * <code>fixed32 testFixed32 = 9;</code>
       * @param value The testFixed32 to set.
       * @return This builder for chaining.
       */
      public Builder setTestFixed32(int value) {
        
        testFixed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *固定字节数的类型
       * </pre>
       *
       * <code>fixed32 testFixed32 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestFixed32() {
        
        testFixed32_ = 0;
        onChanged();
        return this;
      }

      private long testFixed64_ ;
      /**
       * <code>fixed64 testFixed64 = 10;</code>
       * @return The testFixed64.
       */
      @java.lang.Override
      public long getTestFixed64() {
        return testFixed64_;
      }
      /**
       * <code>fixed64 testFixed64 = 10;</code>
       * @param value The testFixed64 to set.
       * @return This builder for chaining.
       */
      public Builder setTestFixed64(long value) {
        
        testFixed64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 testFixed64 = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestFixed64() {
        
        testFixed64_ = 0L;
        onChanged();
        return this;
      }

      private int testSFixed32_ ;
      /**
       * <code>sfixed32 testSFixed32 = 11;</code>
       * @return The testSFixed32.
       */
      @java.lang.Override
      public int getTestSFixed32() {
        return testSFixed32_;
      }
      /**
       * <code>sfixed32 testSFixed32 = 11;</code>
       * @param value The testSFixed32 to set.
       * @return This builder for chaining.
       */
      public Builder setTestSFixed32(int value) {
        
        testSFixed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 testSFixed32 = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestSFixed32() {
        
        testSFixed32_ = 0;
        onChanged();
        return this;
      }

      private long testSFixed64_ ;
      /**
       * <code>sfixed64 testSFixed64 = 12;</code>
       * @return The testSFixed64.
       */
      @java.lang.Override
      public long getTestSFixed64() {
        return testSFixed64_;
      }
      /**
       * <code>sfixed64 testSFixed64 = 12;</code>
       * @param value The testSFixed64 to set.
       * @return This builder for chaining.
       */
      public Builder setTestSFixed64(long value) {
        
        testSFixed64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 testSFixed64 = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestSFixed64() {
        
        testSFixed64_ = 0L;
        onChanged();
        return this;
      }

      private boolean testBool_ ;
      /**
       * <pre>
       *其他类型
       * </pre>
       *
       * <code>bool testBool = 13;</code>
       * @return The testBool.
       */
      @java.lang.Override
      public boolean getTestBool() {
        return testBool_;
      }
      /**
       * <pre>
       *其他类型
       * </pre>
       *
       * <code>bool testBool = 13;</code>
       * @param value The testBool to set.
       * @return This builder for chaining.
       */
      public Builder setTestBool(boolean value) {
        
        testBool_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他类型
       * </pre>
       *
       * <code>bool testBool = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestBool() {
        
        testBool_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object testStr_ = "";
      /**
       * <code>string testStr = 14;</code>
       * @return The testStr.
       */
      public java.lang.String getTestStr() {
        java.lang.Object ref = testStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          testStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string testStr = 14;</code>
       * @return The bytes for testStr.
       */
      public com.google.protobuf.ByteString
          getTestStrBytes() {
        java.lang.Object ref = testStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          testStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string testStr = 14;</code>
       * @param value The testStr to set.
       * @return This builder for chaining.
       */
      public Builder setTestStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        testStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string testStr = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestStr() {
        
        testStr_ = getDefaultInstance().getTestStr();
        onChanged();
        return this;
      }
      /**
       * <code>string testStr = 14;</code>
       * @param value The bytes for testStr to set.
       * @return This builder for chaining.
       */
      public Builder setTestStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        testStr_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString testBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes testBytes = 15;</code>
       * @return The testBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTestBytes() {
        return testBytes_;
      }
      /**
       * <code>bytes testBytes = 15;</code>
       * @param value The testBytes to set.
       * @return This builder for chaining.
       */
      public Builder setTestBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        testBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes testBytes = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestBytes() {
        
        testBytes_ = getDefaultInstance().getTestBytes();
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList listInt_ = emptyIntList();
      private void ensureListIntIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          listInt_ = mutableCopy(listInt_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 listInt = 16;</code>
       * @return A list containing the listInt.
       */
      public java.util.List<java.lang.Integer>
          getListIntList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(listInt_) : listInt_;
      }
      /**
       * <code>repeated int32 listInt = 16;</code>
       * @return The count of listInt.
       */
      public int getListIntCount() {
        return listInt_.size();
      }
      /**
       * <code>repeated int32 listInt = 16;</code>
       * @param index The index of the element to return.
       * @return The listInt at the given index.
       */
      public int getListInt(int index) {
        return listInt_.getInt(index);
      }
      /**
       * <code>repeated int32 listInt = 16;</code>
       * @param index The index to set the value at.
       * @param value The listInt to set.
       * @return This builder for chaining.
       */
      public Builder setListInt(
          int index, int value) {
        ensureListIntIsMutable();
        listInt_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 listInt = 16;</code>
       * @param value The listInt to add.
       * @return This builder for chaining.
       */
      public Builder addListInt(int value) {
        ensureListIntIsMutable();
        listInt_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 listInt = 16;</code>
       * @param values The listInt to add.
       * @return This builder for chaining.
       */
      public Builder addAllListInt(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureListIntIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listInt_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 listInt = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearListInt() {
        listInt_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> testMap_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetTestMap() {
        if (testMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TestMapDefaultEntryHolder.defaultEntry);
        }
        return testMap_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableTestMap() {
        onChanged();;
        if (testMap_ == null) {
          testMap_ = com.google.protobuf.MapField.newMapField(
              TestMapDefaultEntryHolder.defaultEntry);
        }
        if (!testMap_.isMutable()) {
          testMap_ = testMap_.copy();
        }
        return testMap_;
      }

      public int getTestMapCount() {
        return internalGetTestMap().getMap().size();
      }
      /**
       * <pre>
       *字典Dictionary
       * </pre>
       *
       * <code>map&lt;int32, string&gt; testMap = 17;</code>
       */

      @java.lang.Override
      public boolean containsTestMap(
          int key) {
        
        return internalGetTestMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTestMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getTestMap() {
        return getTestMapMap();
      }
      /**
       * <pre>
       *字典Dictionary
       * </pre>
       *
       * <code>map&lt;int32, string&gt; testMap = 17;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, java.lang.String> getTestMapMap() {
        return internalGetTestMap().getMap();
      }
      /**
       * <pre>
       *字典Dictionary
       * </pre>
       *
       * <code>map&lt;int32, string&gt; testMap = 17;</code>
       */
      @java.lang.Override

      public java.lang.String getTestMapOrDefault(
          int key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetTestMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *字典Dictionary
       * </pre>
       *
       * <code>map&lt;int32, string&gt; testMap = 17;</code>
       */
      @java.lang.Override

      public java.lang.String getTestMapOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetTestMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTestMap() {
        internalGetMutableTestMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *字典Dictionary
       * </pre>
       *
       * <code>map&lt;int32, string&gt; testMap = 17;</code>
       */

      public Builder removeTestMap(
          int key) {
        
        internalGetMutableTestMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableTestMap() {
        return internalGetMutableTestMap().getMutableMap();
      }
      /**
       * <pre>
       *字典Dictionary
       * </pre>
       *
       * <code>map&lt;int32, string&gt; testMap = 17;</code>
       */
      public Builder putTestMap(
          int key,
          java.lang.String value) {
        
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableTestMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *字典Dictionary
       * </pre>
       *
       * <code>map&lt;int32, string&gt; testMap = 17;</code>
       */

      public Builder putAllTestMap(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableTestMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GamePlayerTest.TestMsg)
    }

    // @@protoc_insertion_point(class_scope:GamePlayerTest.TestMsg)
    private static final GamePlayerTest.Test.TestMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GamePlayerTest.Test.TestMsg();
    }

    public static GamePlayerTest.Test.TestMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestMsg>
        PARSER = new com.google.protobuf.AbstractParser<TestMsg>() {
      @java.lang.Override
      public TestMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GamePlayerTest.Test.TestMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GamePlayerTest_TestMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GamePlayerTest_TestMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GamePlayerTest_TestMsg_TestMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GamePlayerTest_TestMsg_TestMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\016GamePlayerTest\"\240\003\n\007TestMsg" +
      "\022\r\n\005testF\030\001 \001(\002\022\r\n\005testD\030\002 \001(\001\022\021\n\ttestIn" +
      "t32\030\003 \001(\005\022\021\n\ttestInt64\030\004 \001(\003\022\022\n\ntestSInt" +
      "32\030\005 \001(\021\022\022\n\ntestSInt64\030\006 \001(\022\022\022\n\ntestUInt" +
      "32\030\007 \001(\r\022\021\n\ttestULong\030\010 \001(\004\022\023\n\013testFixed" +
      "32\030\t \001(\007\022\023\n\013testFixed64\030\n \001(\006\022\024\n\014testSFi" +
      "xed32\030\013 \001(\017\022\024\n\014testSFixed64\030\014 \001(\020\022\020\n\010tes" +
      "tBool\030\r \001(\010\022\017\n\007testStr\030\016 \001(\t\022\021\n\ttestByte" +
      "s\030\017 \001(\014\022\017\n\007listInt\030\020 \003(\005\0225\n\007testMap\030\021 \003(" +
      "\0132$.GamePlayerTest.TestMsg.TestMapEntry\032" +
      ".\n\014TestMapEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GamePlayerTest_TestMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GamePlayerTest_TestMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GamePlayerTest_TestMsg_descriptor,
        new java.lang.String[] { "TestF", "TestD", "TestInt32", "TestInt64", "TestSInt32", "TestSInt64", "TestUInt32", "TestULong", "TestFixed32", "TestFixed64", "TestSFixed32", "TestSFixed64", "TestBool", "TestStr", "TestBytes", "ListInt", "TestMap", });
    internal_static_GamePlayerTest_TestMsg_TestMapEntry_descriptor =
      internal_static_GamePlayerTest_TestMsg_descriptor.getNestedTypes().get(0);
    internal_static_GamePlayerTest_TestMsg_TestMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GamePlayerTest_TestMsg_TestMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
